language: php

before_install:
  - git submodule update --init --recursive
  - git clone git://github.com/jbboehr/libmustache.git mustache
  - cd mustache
  - autoreconf -i && ./configure && make && sudo make install
  - cd ..

php:
  - 5.3
  - 5.4
  - 5.5

script:
  - phpize
  - ./configure --enable-mustache
  - make
  - echo n | make test
